name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: use nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      
      - name: create env file
        run: |
          touch .env
          echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
          
      - name: install dependencies
        run: yarn
      - run: yarn test
      - run: yarn build
